### ISSUE TITLE
OAuth issue

### ISSUE THREAD

**Issue by iAugux** [tumblr/TMTumblrSDK#120]
Hi,
Seems newly registered Tumblr accounts are bundled with Yahoo accounts, and when you try to authorize via OAuth, the URL will automatically redirect to "yahoo.com", resulting in unsuccessful authorization.

I also notice that the official iOS Tumblr client works file with this, when you try to log in with a newly registered account, the official Tumblr will also redirect to "yahoo.com" to authorize, like this:
![image 1](https://cloud.githubusercontent.com/assets/7555616/20400183/b01e728c-ad2e-11e6-822b-f75f011c3b95.jpg)
</br>
</br>

Log in with previously registered account (not bundled with Yahoo) , it will show a traditional web page:
</br>
![image 2](https://cloud.githubusercontent.com/assets/7555616/20400398/804dbba2-ad2f-11e6-8b2a-a8f83b55b4b8.jpg)

</br>
</br>

But there is no documentation to tell us how to deal with this problem by our own.
When I try to log in with a newly registered account via OAuth, it just shows a logged in web page. How can i grab the token to my App?

Thank you very much!

**Comment by ceyko** [comment]
@iAugux thanks for this report. This does look like a regression, and we're digging into it right now. In the meantime, it seems that this should only affect users who are not logged in. If you are already logged in to Tumblr, you should be able to proceed with the normal OAuth flow, so you may be able to use this as a temporary workaround.

Additionally, if the Tumblr app is installed, and you are opening the URL directly, and not displaying it in a web view, the Tumblr app should instead intercept the Universal Link, and you should be able to complete the flow.

We're currently working on the fix for the not-logged-in users in a webview, and will keep this thread updated.

**Comment by iAugux** [comment]
@ceyko Thanks for your reply! Looking forward to your solution...

**Comment by ceyko** [comment]
@iAugux we've fixed this on the backend, and you should now have no problems completing the flow, regardless of if the login uses Yahoo or Tumblr.

If you're still having issues, feel free to reopen.

**Comment by iAugux** [comment]
@ceyko It works. Thank you!
